backend:
  name: git-gateway
  branch: main
media_folder: "public/assets/books"
public_folder: "/assets/books" 
collections:
  - name: "book" # Used in routes, e.g., /admin/collections/blog
    label: "Book" # Used in the UI
    folder: "src/books" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: "About the Book"
        name: "aboutBook"
        widget: "object"
        collapsed: true
        fields: 
          - {label: "Title", name: "bookTitle", widget: "string"}
          - {label: "Slug", name: "slug", widget: "string"}
          - {label: "Author", name: "author", widget: "string"}
          - {label: "Book Cover Image", name: "coverImage", widget: "image"}
          - {label: "Book Cover Alt", name: "coverImageAlt", widget: "string"}

      - label: "Book Sluts Info"
        name: "bookslutsInfo"
        widget: "object"
        collapsed: true
        fields: 
          - {label: "Book Number", name: "bookNumber", widget: "string"}
          - {label: "Rating", name: "rating", widget: "number"}
          - {label: "Date Read", name: "dateRead", widget: "date"}
          - {label: "Date Read Alt", name: "dateReadAlt", widget: "string"}
          - {label: "Selected By", name: "bookslutName", widget: "string"}
          - {label: "Selected By, Image", name: "bookslutImage", widget: "image"}
          - {label: "Colour - Primary", name: "colourPrimary", widget: "color", enableAlpha: true, allowInput: true}
          - {label: "Colour - Secondary", name: "colourSecondary", widget: "color", enableAlpha: true, allowInput: true}

      - label: "Book Content"
        name: "bookContent"
        widget: "object"
        collapsed: true
        fields: 
          # - {label: "Book Summary", name: "summary", widget: "list", fields: {
          #   label: "Paragraph", name: "paragraph", widget: "string"
          # }}
          # - {label: "Highlights", name: "highlights", widget: "list", fields: {
          #   label: "Highlight", name: "highlight", widget: "string"
          # }}
          - {label: "Behind the Scenes Image", name: "btsImage", widget: "image"}


      - label: "Next Book"
        name: "nextBook"
        widget: "object"
        collapsed: true
        fields: 
          - {label: "Name", name: "nextBookName", widget: "string"}
          - {label: "Slug", name: "nextBookSlug", widget: "string"}
          - {label: "Cover Image", name: "nextBookCover", widget: "image"}
          - {label: "Colour", name: "nextBookColour", widget: "color", enableAlpha: true, allowInput: true}